import type { Metadata } from 'next'
import { createClient } from "@/supabase/utils/server";
import { cookies } from "next/headers";
import './style/globals.css'
import Menu from '@/components/menu'
import { CategoryType } from '@/lib/types'
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Harry Graphics',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createClient(cookies());

  /**** get categories ****/
  const categoriesRes = await supabase.from('categories').select().order('updated_at', { ascending: false });;
  const categories: CategoryType[] = categoriesRes.data || []

  /**** get user data ****/
  const { data } = await supabase.auth.getSession()

  const userRes = await supabase.from('users').select().eq('id', data.session?.user.id).single();

  return (
    <html lang="en">
      <body>
        <script>0</script>
        <Menu categories={categories} user={userRes.data}/>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
